import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./styles/globals.css";

const shareTechMono = IBM_Plex_Mono({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${shareTechMono.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
